# Generated by Django 5.2.8 on 2025-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pomodoro_Engine_Module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='actual_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=20),
        ),
    ]
